#!/bin/bash

#ip_puerto_servico=$(netstat -ant | awk '{print $4,$5}' | awk '{print $1}' | tr -d "a-zA-Z\-\_*()")
#pid_servicios=$(netstat -anp | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | awk '{print $NF}' | cut -d "/" -f1 | tr -d "-" | sort -nu)
#ip_mas_pid=$(netstat -anp | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | awk '{print $4,$NF}' | cut -d "/" -f1 | sort -u)


#Colores
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"


echo "$(netstat -anp | grep '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | awk '{print $4,$NF}' | cut -d "/" -f1 | sort -k2 -n -u)" | while read line; do

	echo "Local Address: "$(echo $line | cut -d " " -f1) "--> PID:" $(echo $line | awk '{print $NF}')
	pid=$(echo $line | awk '{print $NF}')
	for i in $pid; do

	if  [[ "$(echo $pid)" =~ ^[0-9]+$ ]] ; then
		user=$(ps faux | awk '{print $1,$2}' | grep $pid)
		if [ $(echo $user | awk '{print $1}') == "root" ]; then
			echo -e "User: ${redColour}\e[103m$(echo $user | awk '{print $1}')\e[49m${endColour}\n"

		elif [ $(echo $user | awk '{print $1}') == "mysql" ]; then
		        echo -e "User: ${greenColour} $(echo $user | awk '{print $1}') ${endColour}\n"
		else

		echo -e "User: ${blueColour} $(echo $user | awk '{print $1}')${endColour}\n"
		fi
	fi

	if ! [[ "$(echo $pid)" =~ ^[0-9]+$ ]] ; then
		echo -e "No PID \n"
	fi


	done
done

#Dot/@kx1z0
